# Generated by Django 4.1.3 on 2022-12-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0002_alter_return_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
