# Generated by Django 4.1.3 on 2022-12-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0003_alter_purchase_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date_of_purchase',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
